= Аннотации

*Аннотация* в Java - элемент языка, позволяющий прикрепить некоторую информацию к _другим_ элементам языка.

Наиболее известная аннотация - https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Override.html[`@Override`].
Она добавляется к методам, которые переопределяют методы супер-класса или интерфейса.
Её отсутствие не вызовет ошибки компиляции, однако её присутствие у метода, не переопределяющего метод предка, вызовет ошибку компиляции.
Здесь можно вспомнить тот самый пример с `equals`:

[source,java]
----
public class Person {
    @Override
    public boolean equals(Person person) {
        //                ^^^^^^
        //               Должен быть Object
        return super.equals(obj);
    }
}
----

Среди других аннотаций пакета `java.lang` находятся:

* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Deprecated.html[`@Deprecated`] - пометка, что _элемент_ устарел и не должен использоваться
* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/FunctionalInterface.html[`@FunctionalInterface`] выражает намерение программиста сделать из интерфейса _функциональный интерфейс_ (тот, у которого один `abstract` ный метод), в противном случае - выдать ошибку компиляции
* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/SafeVarargs.html[`@SafeVarargs`] - говорит, что тело метода *не* будет выполнять небезопасных операций с vararg типами параметров (это связано с generic'ами).
См. пример в javadoc + https://stackoverflow.com/questions/14231037/java-safevarargs-annotation-does-a-standard-or-best-practice-exist[Java SafeVarargs annotation, does a standard or best practice exist?])
* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/SuppressWarnings.html[`@SuppressWarnings`] - сообщает компилятору, что предупреждение необходимо подавить.
Наиболее известный частный случай - https://stackoverflow.com/questions/1129795/what-is-suppresswarnings-unchecked-in-java[`@SuppressWarnings("unchecked")`]

== Объявление аннотаций

В java нет ключевого слова https://kotlinlang.org/docs/reference/annotations.html[`annotation`].
Вместо этого используется `@` + `interface`.
Например:

[source,java]
----
public @interface Wow {
}
----

https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-9.6[_Аннотации - на самом деле интерфейсы_]

* В примере кода выше объявлена аннотация `Wow`.
* Она _практически_ не будет видна во время исполнения (см. <<retention>>)
* Она может быть добавлена _практически_ (<<targetDefaultValue, Target по умолчанию>>) к любому элементу, например:

Пример:

[source,java]
----
@Wow
public class Something {
    @Wow
    private final Set<String> strings;

    @Wow
    public Something(@Wow Set<String> stringsSet) {
        this.strings = stringsSet;
    }
}

----

В примере выше проаннотированы и класс, и поле, и конструктор, и его параметр.

[.small]
_Если доводить их использование до абсурда, то может получиться https://twitter.com/lukaseder/status/711612663202238464[что-то такое]_

== Методы аннотаций

Аннотации могут иметь _методы_ (аннотации - интерфейсы).

Пример:

[source,java]
----
public @interface Scheduled {
    int delayMillis();

    int rateMillis();
}
----

Использоваться эти методы могут примерно следующим образом:

[source,java]
----
public class ScheduledUsage {
    @Scheduled(delayMillis = 100, rateMillis = 1000)
    public void scheduledMethod() {
    }
}
----

=== Значения по умолчанию

Методы могут иметь значения по умолчанию, для этого используется ключевое слово `default`:

[source,java]
----
public @interface Scheduled {
    int delayMillis();

    int rateMillis() default 1000;
}
----

Тогда `rateMillis` указывать будет необязательно.
Вместо этого будет использоваться значение по умолчанию - `1000`:

[source,java]
----
public class ScheduledUsage {
    @Scheduled(delayMillis = 100)
    public void scheduledMethod() {
    }
}
----

=== Возвращаемые значения методов

==== Типы

Методы аннотаций могут иметь *только* один из следующих *типов* возвращаемого значения:

* Аннотация
* Примитив (`int`, `long`, `float` и т.д.)
* `java.lang.Class`
* `enum`
* `java.lang.String`
* Массивы того, что перечислено _выше_

==== Ограничения на значения

Возвращаемые значения могут быть только *константами*, т.е. следующий пример *не* скомпилируется:

[source,java]
----
public class ScheduledUsage {
    private final int delay;
    private final int rate;

    public ScheduledUsage(int delay, int rate) {
        this.delay = delay;
        this.rate = rate;
    }

    @Scheduled(delayMillis = delay, rateMillis = rate)
    // java: element value must be a constant expression
    public void scheduledMethod() {
    }
}
----

TIP: Если попробовать посмотреть на это с другой стороны, то: аннотации добавляются к элементам класса, а *не* к их _экземплярам_

== `java.lang.annotation`

`java.lang.annotation` - пакет, добавляющий поддержку аннотаций в сам язык.
Как ни странно, часть этой поддержки тоже добавляется через аннотации.

В этом пакете находятся:

* `interface` https://stackoverflow.com/questions/1129795/what-is-suppresswarnings-unchecked-in-java[`Annotation`].
Все аннотации его реализуют
* Ошибки / исключения: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/AnnotationTypeMismatchException.html[`AnnotationTypeMismatchException`], https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/IncompleteAnnotationException.html[`IncompleteAnnotationException`], https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/AnnotationFormatError.html[`AnnotationFormatError`]
* Другие аннотации:
** https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Documented.html[`@Documented`]
** https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Inherited.html[`@Inherited`]
** https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Native.html[`@Native`]
** https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Repeatable.html[`@Repeatable`]
** https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Retention.html[*`@Retention`*] - аннотация, позволяющая указать, "до какого этапа жизни" аннотации она должна присутствовать (Подробнее - в <<retention,retention>>)
** https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Native.html[*`@Target`*] - аннотация, ставящаяся над другой аннотацией.
Она позволяет уточнить / ограничить места, где данная _аннотированная_ аннотация может быть добавлена

[.small]
_Наиболее важные элементы в списке выше *выделены*._

[#retention]
== Retention

Аннотации могут быть использованы для разных целей:

. Генерация исходного `java`-кода на этапе компиляции (так делает, например, https://dagger.dev/[Dagger], https://micronaut.io/[Micronaut])
. Использование информации *во время исполнения*.
Так делают https://github.com/FasterXML/jackson[Jackson], https://github.com/google/gson[Gson], https://square.github.io/retrofit/[Retrofit]

* Пункт 1 соответствует `RetentionPolicy.SOURCE`.
* Второй - `RetentionPolicy.RUNTIME`.
* Кроме этого, есть нечто посередине - `RetentionPolicy.CLASS`.
Это - значение *по умолчанию*

_См. https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/RetentionPolicy.html[`RetentionPolicy`]

TIP: Для генерации исходного java-кода на этапе компиляции входная точка - https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/package-summary.html[Annotation Processing API].
См также: https://github.com/gunnarmorling/awesome-annotation-processing[Awesome Java Annotation Processing]

=== Сравнение RetentionPolicy

.Таблица сравнения RetentionPolicy
|===
|RetentionPolicy | Описание | Остается в класс-файле | Доступна во время исполнения
| `SOURCE` | Отбрасываются после компиляции | icon:times[] | icon:times[]
| `CLASS` | Отбрасывается на этапе _загрузки класса_ | icon:check[] | Условно: если найти класс-файл и прочитать его
| `RUNTIME` | Аннотация всегда доступна через reflection *во время исполнения* | icon:check[] | icon:times[]
|===

==== Мини-эксперимент

[source,java]
----
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@Retention(RetentionPolicy.CLASS)
@interface RetainedInClass {
}

@Retention(RetentionPolicy.SOURCE)
@interface RetainedInSource {
}

@Retention(RetentionPolicy.RUNTIME)
@interface RetainedAtRuntime {
}

@RetainedInClass
@RetainedAtRuntime
@RetainedInSource
public class Annotations {
    public static void main(String[] args) {
        boolean retainedInClassIsVisible = Annotations.class.getAnnotation(RetainedInClass.class) != null;
        boolean retainedInSourceIsVisible = Annotations.class.getAnnotation(RetainedInSource.class) != null;
        boolean retainedAtRuntime = Annotations.class.getAnnotation(RetainedAtRuntime.class) != null;
        System.out.println("RetainedInClass is visible? " + retainedInClassIsVisible);
        System.out.println("RetainedInSource is visible? " + retainedInSourceIsVisible);
        System.out.println("RetainedAtRuntime is visible? " + retainedAtRuntime);
    }
}
----

* Аннотация `RetainedInClass` имеет `retention = CLASS`, `RetainedInSource` - `SOURCE`, `RetainedAtRuntime`
* Над классом `Annotations` висят все три
* В методе `main` производится попытка получить аннотации через reflection api (см. https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html#getAnnotation(java.lang.Class)[`Class#getAnnotation`])

Результат:

[source,text]
----
RetainedInClass is visible? false
RetainedInSource is visible? false
RetainedAtRuntime is visible? true
----

_То есть, как и ожидалось, во время исполнения видна только аннотация с `RetentionPolicy.RUNTIME`._

==== Что в class файле?

Для просмотра класс файла можно воспользоваться утилитой https://docs.oracle.com/en/java/javase/11/tools/javap.html[javap], поставляемой вместе с jdk.

[source,bash]
----
$ javap -v Annotations.class
----

* `-v` - выводить подробно
* `Annotations.class` - файл, полученный после компиляции

Часть вывода:

[source,text]
----
RuntimeVisibleAnnotations:
  0: #32()
    ru.hse.annotations.RetainedAtRuntime
RuntimeInvisibleAnnotations:
  0: #34()
    ru.hse.annotations.RetainedInClass
----

`javap` говорит, что в `.class` файле есть:

* Аннотация, видимая во время исполнения, - `RetainedAtRuntime`
* Аннотация, которую во время исполнения не видно, это - `RetainedInClass`
* `RetainedInSource` не упоминается в контексте _использования_ аннотации в качестве аннотации

== Места использования

Аннотации могут быть использованы в совершенно различных местах.
Исчерпывающий список, как и всегда в подобных случаях, приводится в JLS - спецификации языка Java, https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-9.6.4.1[§ 9.6.4.1. `@Target`]:

. Объявления модулей (`module`, _пока не проходили_, `ElementType.MODULE`)
. Объявление пакетов (`package`, `ElementType.PACKAGE`)
. Объявления типов (`class`, `interface`, `enum`, аннотации. `ElementType.TYPE` + для аннотаций `ElementType.ANNOTATION_TYPE`)
. Объявления методов (`ElementType.METHOD`)
. Объявления конструкторов (`ElementType.CONSTRUCTOR`)
. Объявления generic классов, интерфейсов, методов, конструкторов (`ElementType.TYPE_PARAMETER`)
. Объявления полей (`ElementType.FIELD`)
. Формальные параметры и параметры объявления исключений (TODO: что это?) (`ElementType.PARAMETER`)
. Объявления локальных переменных (`ElementType.LOCAL_VARIABLE`)

=== Пример использования аннотации для локальной переменной

[source,java]
----
public class Main {
    public static void main(String[] args){
        List<String> stringList = Collections.emptyList();
        @SuppressWarnings({"RawTypeCanBeGeneric", "rawtypes"})
        List l = stringList;
    }
}
----

TIP: В стандартной библиотеке это соответствует перечислению https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/ElementType.html[`ElementType`]

=== https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Target.html[`@Target`]

Аннотация `@Target` - одна из особых аннотаций языка.
Она позволяет ограничить, где именно аннотация, _аннотированная аннотацией `@Target`,_ может быть использована.

Пример:

[source,java]
----
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELDS)
public @interface MakesSenseOnlyAtFields {
}
----

[source,java]
----
public class User {
    @MakesSenseOnlyAtFields
    private final String username;

    public User(String username) {
        this.username = username;
    }
}
----

* `@Target` аннотации - `FIELDS`
* Она добавлена к полю, поэтому код успешно комплируется
* При попытке добавить её к классу, т.е.:

[source,java]
----
@MakesSenseOnlyAtFields
public class User {
}
----

возникает ошибка компиляции:

[source,text]
----
java: annotation type not applicable to this kind of declaration
----

[#targetDefaultValue]
=== `target` по умолчанию

В случае, если `@Target` не будет задан, то будет использоваться значение по умолчанию - везде, кроме параметров типов и type contexts (TODO: что это?).

* Параметры типов - это про generic'и:

[source,java]
----
Set<@Wow String> strings;
//  ^^^
----

* Type contexts - непонятно (TODO)

== Работа с аннотациями во время исполнения

Аннотации сами по себе чаще всего ничего не значат, их должен кто-то обрабатывать.

TIP: Это важно понимать, когда вы столкнётесь с `@Transactional` / `@Cacheable` или `@OneToMany`

TIP: Аннотации, упомянутые до этого, - *особые*, т.к. они тесно связаны с самим языком

Обработка аннотаций в общем случае зависит от логики, которую необходимо добавить по предоставленной с помощью аннотаций информации.

Это может выглядеть следующим образом:

. Получить `Class<?>` объекта, который нужно обработать.
. Прочитать аннотации.
. Выполнить необходимую логику (Ниже будет пример).

Для чтения аннотаций через reflection можно использовать интерфейс https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/AnnotatedElement.html[`AnnotatedElement`].

Его реализуют `Class`, `Constructor`, `Field`, `Method` и другие.

Пример чтения аннотаций со всех методов:

[source,java]
----
package ru.hse.annotations;

import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

public class ScheduledScanner {
    @Scheduled(delayMillis = 100, rateMillis = 100) // 1
    public void scheduled1() {
    }

    @Scheduled(delayMillis = 200, rateMillis = 200) // 2
    public void scheduled2() {
    }

    @Scheduled(delayMillis = 300, rateMillis = 300) // 3
    public void scheduled3() {
    }

    private static List<Scheduled> getSchedules(Object o) { // 4
        Class<?> clazz = o.getClass(); // 5
        Method[] methods = clazz.getMethods(); // 6
        return Arrays.stream(methods)
                .map(method -> method.getAnnotation(Scheduled.class))// 7
                .filter(Objects::nonNull) // 8
                .collect(Collectors.toList());
    }

    public static void main(String[] args) {
        ScheduledScanner scheduledScanner = new ScheduledScanner();
        List<Scheduled> schedules = getSchedules(scheduledScanner);
        schedules.forEach(scheduled -> System.out.println("@Scheduled (delay = " // 9
                + scheduled.delayMillis() + ", rate = " + scheduled.delayMillis() + ")"));
    }
}
----

* Методы `1`, `2`, `3` помечены аннотацией `@Scheduled`
* `4`: метод принимает *`Object`* и возвращает список аннотаций
* `5`: `getClass` возвращает класс `o`
* `6`: возвращает все методы
* `7`: `method.getAnnotation` вернет аннотацию или `null`, если её нет
* `8`: если был метод без аннотации, то полученный `null` нужно пропустить
* `9`: вывод полученных значений

Вывод:

[source,text]
----
@Scheduled (delay = 100, rate = 100)
@Scheduled (delay = 200, rate = 200)
@Scheduled (delay = 300, rate = 300)
----

TIP: См. также: https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/index.html[Java Reflection API] + занятия в первом семестре

== Наследование аннотаций и https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/index.html[`@Inherited`]

Аннотация https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/index.html[`@Inherited`] показывает, что она должна быть унаследована.
Т.е. при запросе аннотации у `class` 'а будут проверены все супер-классы

TIP: А интерфейсы?
TODO

Пример:

[source,java]
----
@Retention(RetentionPolicy.RUNTIME)
@Inherited // 1
public @interface Persistable {
}

@Persistable // 2
public abstract class AbstractEntity {
}

public class Task extends AbstractEntity { // 3
}

public class InheritedDemo {
    public static void main(String[] args) {
        Persistable persistable = Task.class.getAnnotation(Persistable.class); // 4
        System.out.println(persistable);
    }
}
----

* `1`: аннотация помечена, как _наследуемая_
* `2`: `AbstractEntity` в свою очередь помечена, как `@Persistable`
* `3`: `Task extends AbstractEntity` без добавления аннотации
* `4`: Запрос аннотации через `Class#getAnnotation`

Вывод:

[source,text]
----
@ru.hse.annotations.Persistable()
----

Без `@Inherited` вывод был следующим:

[source,text]
----
null
----

== Повторяемые аннотации и https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Repeatable.html[`@Repeatable`]

Иногда может быть полезно применить одну и ту же аннотацию несколько раз, например:

[source,java]
----
@Retention(RetentionPolicy.RUNTIME)
public @interface RunEveryDayAt {
    int hours() default 0;
}

public class Cron {
    @RunEveryDayAt(hours = 11)
    @RunEveryDayAt(hours = 23)
    public void compactSpace() {
    }
}
----

Однако, класс `Cron` просто не скомпилируется с ошибкой:

[source,text]
----
java: ru.hse.annotations.RunEveryDayAt is not a repeatable annotation type
----

Чтобы это заработало необходимо:

. объявить другую аннотацию, которая:
.. имеет метод, который:
... возвращает массив _исходных_ аннотаций
... назван <<methodValue, `value`>>
.. не имеет других методов без указания `default` значений
. пометить исходную аннотацию как `@Repeatable` указав в ней аннотацию, полученную на предыдущем шаге

[source,java]
----
@Retention(RetentionPolicy.RUNTIME)
public @interface RunEveryDayAts {
    RunEveryDayAt[] value() default {}; // 1
}

@Retention(RetentionPolicy.RUNTIME)
@Repeatable(RunEveryDayAts.class) // 2
public @interface RunEveryDayAt {
    int hours() default 0;
}
----

* Аннотация `RunEveryDayAts` - аннотация, получанная на первом шаге
* `1`: Метод `value` возвращает массив _исходных_ аннотаций.
* `2`: Исходная аннотация помечена, как `Repeatable` с указанием контейнерной аннотации `RunEveryDayAts`

Тогда следующий код:

[source,java]
----
public class Main {
    public static void main(String[] args) throws NoSuchMethodException, SecurityException {
        Method method = Cron.class.getMethod("compactSpace");
        System.out.println(Arrays.toString(method.getAnnotationsByType(RunEveryDayAt.class)));
    }
}
----

выведет:

[source,text]
----
[@ru.hse.annotations.RunEveryDayAt(hours=11), @ru.hse.annotations.RunEveryDayAt(hours=23)]
----

CAUTION: `getAnnotation(RunEveryDayAt.class)` в данном случае вернёт `null`

== `@Documented`

<<metaAnnotations, Мета-аннотация>>, которая даёт _подсказку_ инструментам, генерирующим документацию, что использование аннотации с `@Documented` должно быть задокументировано.

См. также:

* https://stackoverflow.com/q/5592703/6486622[`@Documented` annotation in java]

== `@Native`

Аннотация, сообщающая что _поле_ может быть использовано в `native` коде.

См. также:

* https://softwareengineering.stackexchange.com/questions/218538/why-would-someone-use-native-annotations[Why would someone use `@Native` annotations?]

[#methodValue]
== Метод `value`

== Особенности синтаксиса

[#metaAnnotations]
== Мета-аннотации

Мета-аннотация - аннотация, которая ставится над другой аннотацией.

Все аннотации, у которых `target = ElementType.ANNOTATION_TYPE` - мета-аннотации.
TODO

Мета-аннотации из JDK:

* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Target.html[`@Target`]
* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Inherited.html[`@Inherited`]

== Мы не меняем семантику языка
